#
# build.yml - GitHub build action for AVRDUDE
# Copyright (C) 2021 Marius Greuel
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

name: Build

on:
  push:
    branches-ignore:
      - 'onlinedocs'
  pull_request:
    branches-ignore:
      - 'onlinedocs'
  workflow_call:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: >-
          sudo apt-get update

          sudo apt-get install -y
          build-essential
          cmake
          flex
          bison
          libelf-dev
          libusb-dev
          libusb-1.0-0-dev
          libhidapi-dev
          libftdi1-dev
          libreadline-dev
          libudev-dev
      - name: Configure
        run: >-
          cmake
          -D DEBUG_CMAKE=1
          -D HAVE_LINUXGPIO=1
          -D HAVE_LINUXSPI=1
          -D CMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++"
          -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -D USE_STATIC_LIBS=ON
          -D CMAKE_VERBOSE_MAKEFILE=ON
          -B build
      - name: Build
        run: cmake --build build
      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-linux-x86_64
          path: |
            build/
            !**/*.d
            !**/*.o
      - name: Archive executables
        uses: actions/upload-artifact@v2
        with:
          name: avrdude-linux-x86_64
          path: |
            build/src/avrdude
            build/src/avrdude.conf

  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: >-
          brew update

          brew install
          cmake
          flex
          bison
          libelf
          libusb
          hidapi
          libftdi
      - name: Configure
        run: >-
          cmake
          -D CMAKE_C_FLAGS=-I/usr/local/include -pthread -framework Foundation -framework IOKit -framework Cocoa -framework Security
          -D CMAKE_EXE_LINKER_FLAGS=-L/usr/local/Cellar
          -D DEBUG_CMAKE=1
          -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -D USE_STATIC_LIBS=ON
          -D CMAKE_VERBOSE_MAKEFILE=ON
          -B build
      - name: Build
        run: cmake --build build
      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-macos-x86_64
          path: |
            build/
            !**/*.d
            !**/*.o
      - name: Archive executables
        uses: actions/upload-artifact@v2
        with:
          name: avrdude-macos-x86_64
          path: |
            build/src/avrdude
            build/src/avrdude.conf
